import React from "react";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import Button from "@/components/ui/button";
import { OnionTableIcon } from "@/components/icons/svgs";
import Image from "next/image";

type ReportsDetailsProps = {
  reportId: string;
};

const DISPUTES = [
  { id: "DSP-330", type: "Agent Dispute", status: "Open", priority: "High" },
  { id: "DSP-329", type: "Merchant Dispute", status: "In review", priority: "Medium" },
  { id: "DSP-328", type: "Cash Discrepancy", status: "Escalated", priority: "Urgent" },
  { id: "DSP-327", type: "Merchant Dispute", status: "Resolved", priority: "Low" },
];

const STATUS_STYLES: Record<string, string> = {
  Open: "bg-[#E7F6EC] text-[#008A3A]",
  "In review": "bg-[#FEF6E7] text-[#DD900D]",
  Escalated: "bg-[#E5F0FF] text-[#2474D2]",
  Resolved: "bg-[#E7F6EC] text-[#008A3A]",
};

const PRIORITY_STYLES: Record<string, string> = {
  High: "bg-[#D91E18]",
  Medium: "bg-[#E89B00]",
  Urgent: "bg-[#D91E18]",
  Low: "bg-[#D91E18]",
};

const AGGREGATORS = [
  { name: "Mama Nkechi", region: "South-South", activation: 81, payout: "₦306,000" },
  { name: "Obi & Co Ventures", region: "South-West", activation: 72, payout: "₦260,000" },
  { name: "Coastal Partners Team", region: "North-Central", activation: 0, payout: "₦0" },
  { name: "RiverBank Team", region: "South-East", activation: 82, payout: "₦306,000" },
];

const ACTIVATION_STYLES = (activation: number) =>
  activation >= 80 ? "bg-[#008A3A]" : activation > 0 ? "bg-[#E89B00]" : "bg-[#CB1A14]";

function DisputeResolutionReport() {
  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[28px] p-[20px]">
        <div className="grid grid-cols-2 gap-[20px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-DIS" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[12px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[12px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[12px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> 4 cases this period- 1
          open, 1 in review, 1 escalated, 1 resolved. Average resolution time 6 days for closed
          cases
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[760px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[17%]" />
            <col className="w-[21%]" />
            <col className="w-[20%]" />
            <col className="w-[18%]" />
            <col className="w-[24%]" />
          </colgroup>
          <thead>
            <tr className="h-[56px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[13px] font-semibold text-[#6C6C6C]">
              <th className="px-[16px]" scope="col">
                DSP ID
              </th>
              <th className="px-[16px]" scope="col">
                Type
              </th>
              <th className="px-[16px]" scope="col">
                Status
              </th>
              <th className="px-[16px]" scope="col">
                Priority
              </th>
              <th className="px-[16px]" scope="col">
                Opened
              </th>
            </tr>
          </thead>
          <tbody>
            {DISPUTES.map((dispute) => (
              <tr
                key={dispute.id}
                className="h-[66px] border-b border-[#D6D6D6] text-[12px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[16px]">{dispute.id}</td>
                <td className="px-[16px]">{dispute.type}</td>
                <td className="px-[16px]">
                  <span
                    className={`inline-flex min-w-[88px] justify-center rounded-full px-[12px] py-[5px] font-medium ${STATUS_STYLES[dispute.status]}`}
                  >
                    {dispute.status}
                  </span>
                </td>
                <td className="px-[16px]">
                  <span className="inline-flex items-center gap-[6px]">
                    <span
                      className={`h-[8px] w-[8px] rounded-full ${PRIORITY_STYLES[dispute.priority]}`}
                    />
                    <span className={dispute.priority === "Urgent" ? "text-[#CB1A14]" : ""}>
                      {dispute.priority}
                    </span>
                  </span>
                </td>
                <td className="whitespace-nowrap px-[16px]">May 19,2026 at 09:15am</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[12px] p-[20px]">
        <h2 className="text-[14px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[12px] leading-[20px] text-[#6C6C6C]">
          DSP-329 exceeds Ops self-resolution authority and remains with Finance &amp; Risk - 2
          hours remaining on their SLA at time of this report
        </p>
      </div>
    </div>
  );
}

function AggregatorCommissionReport() {
  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[28px] p-[20px]">
        <div className="grid grid-cols-2 gap-[20px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-AGG" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[12px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[12px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[12px] leading-[20px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> 2.79M in pending payouts
          across 3 active aggregators. River bank partners activation rate (31%) is well below
          network average - flagged for review last cycle
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[760px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[17%]" />
            <col className="w-[21%]" />
            <col className="w-[20%]" />
            <col className="w-[24%]" />
            <col className="w-[18%]" />
          </colgroup>
          <thead>
            <tr className="h-[56px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[13px] font-semibold text-[#6C6C6C]">
              <th className="px-[16px]" scope="col">
                Aggregator
              </th>
              <th className="px-[16px]" scope="col">
                Region
              </th>
              <th className="px-[16px]" scope="col">
                Activation
              </th>
              <th className="px-[16px]" scope="col">
                Pending payout
              </th>
              <th className="px-[16px]" scope="col">
                Commission Tier
              </th>
            </tr>
          </thead>
          <tbody>
            {AGGREGATORS.map((aggregator) => (
              <tr
                key={aggregator.name}
                className="h-[66px] border-b border-[#D6D6D6] text-[12px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[16px]">{aggregator.name}</td>
                <td className="px-[16px]">{aggregator.region}</td>
                <td className="px-[16px]">
                  <span className="flex items-center gap-[6px]">
                    <span className="h-[6px] w-[54px] overflow-hidden rounded-full bg-[#E5E5E5]">
                      <span
                        className={`block h-full rounded-full ${ACTIVATION_STYLES(aggregator.activation)}`}
                        style={{ width: `${aggregator.activation}%` }}
                      />
                    </span>
                    <span>{aggregator.activation}%</span>
                  </span>
                </td>
                <td className="px-[16px]">{aggregator.payout}</td>
                <td className="px-[16px]">Standard</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[12px] p-[20px]">
        <h2 className="text-[14px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[12px] leading-[20px] text-[#6C6C6C]">
          Coastal partner team still pending initial approval. RiverBank partners is under review -
          activation trend declining over the last period
        </p>
      </div>
    </div>
  );
}

function MerchantOnboardingReport() {
  const applicationCounts = [
    { category: "OnionSolo", applicants: 1, approved: 0, pending: 1 },
    { category: "OnionCrew", applicants: 1, approved: 0, pending: 1 },
    { category: "OnionMega", applicants: 0, approved: 4, pending: 0 },
  ];
  const applications = [
    { business: "Buchi Phone Repairs", category: "OnionSolo", fee: "1.5%" },
    { business: "Coastal Bites Limited", category: "OnionCrew", fee: "1.2%" },
    { business: "Sweet Havens", category: "OnionMega", fee: "1.3%" },
  ];

  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[24px] p-[16px]">
        <div className="grid grid-cols-2 gap-[16px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-MER" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[11px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[11px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> 2 applications this period,
          both awaiting approval. No OnionMega applications
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[620px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[24%]" />
            <col className="w-[25%]" />
            <col className="w-[25%]" />
            <col className="w-[26%]" />
          </colgroup>
          <thead>
            <tr className="h-[54px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[12px] font-semibold text-[#6C6C6C]">
              <th className="px-[12px]" scope="col">
                Category
              </th>
              <th className="px-[12px]" scope="col">
                Applicants
              </th>
              <th className="px-[12px]" scope="col">
                Approved
              </th>
              <th className="px-[12px]" scope="col">
                Pending
              </th>
            </tr>
          </thead>
          <tbody>
            {applicationCounts.map((item) => (
              <tr
                key={item.category}
                className="h-[55px] border-b border-[#D6D6D6] text-[11px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[12px]">{item.category}</td>
                <td className="px-[12px]">{item.applicants}</td>
                <td className="px-[12px]">{item.approved}</td>
                <td className="px-[12px]">{item.pending}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 className="border-b border-[#E5E7EB] px-[16px] py-[20px] text-[11px] font-semibold text-[#04907E]">
        Application Detail
      </h2>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[620px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[27%]" />
            <col className="w-[27%]" />
            <col className="w-[24%]" />
            <col className="w-[22%]" />
          </colgroup>
          <thead>
            <tr className="h-[54px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[12px] font-semibold text-[#6C6C6C]">
              <th className="px-[12px]" scope="col">
                Business
              </th>
              <th className="px-[12px]" scope="col">
                Category
              </th>
              <th className="px-[12px]" scope="col">
                Status
              </th>
              <th className="px-[12px]" scope="col">
                Assigned Fee
              </th>
            </tr>
          </thead>
          <tbody>
            {applications.map((application) => (
              <tr
                key={application.business}
                className="h-[55px] border-b border-[#D6D6D6] text-[11px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[12px]">{application.business}</td>
                <td className="px-[12px]">{application.category}</td>
                <td className="px-[12px]">
                  <span className="inline-flex rounded-full bg-[#FEF6E7] px-[10px] py-[4px] text-[10px] font-medium text-[#DD900D]">
                    Pending approval
                  </span>
                </td>
                <td className="px-[12px]">{application.fee}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[10px] p-[16px]">
        <h2 className="text-[12px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          Coastal Bites Limited is held on approval, pending a repeat address verification - see KYC
          Approval Log for details
        </p>
      </div>
    </div>
  );
}

function KycApprovalReport() {
  const decisions = [
    {
      applicant: "Ibrahim Musa",
      type: "Personal",
      decision: "Approved",
      reviewer: "Adaeze Chukwu",
    },
    {
      applicant: "Grace Ojo",
      type: "Personal",
      decision: "Rejected - Selfie missing",
      reviewer: "Adaeze Chukwu",
    },
    {
      applicant: "Mama Nkechi",
      type: "Merchant",
      decision: "Approved",
      reviewer: "Ifeoma Ejiofor",
    },
    {
      applicant: "Coastal Bites Limited",
      type: "Merchant",
      decision: "Pending - Address verification failed",
      reviewer: "-/-",
    },
    {
      applicant: "Addobi Chike",
      type: "Personal",
      decision: "Pending - NIN mismatched",
      reviewer: "-/-",
    },
  ];

  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[24px] p-[16px]">
        <div className="grid grid-cols-2 gap-[16px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-KYC" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[11px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[11px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> 5 decisions logged this
          period - 3 approved, 1 rejected, 1 still pending address verification. Rejection rate
          (20%), in line with recent trend.
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[760px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[18%]" />
            <col className="w-[14%]" />
            <col className="w-[29%]" />
            <col className="w-[18%]" />
            <col className="w-[21%]" />
          </colgroup>
          <thead>
            <tr className="h-[54px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[12px] font-semibold text-[#6C6C6C]">
              <th className="px-[12px]" scope="col">
                Applicants
              </th>
              <th className="px-[12px]" scope="col">
                Type
              </th>
              <th className="px-[12px]" scope="col">
                Decision
              </th>
              <th className="px-[12px]" scope="col">
                Reviewer
              </th>
              <th className="px-[12px]" scope="col">
                Opened
              </th>
            </tr>
          </thead>
          <tbody>
            {decisions.map((decision) => (
              <tr
                key={decision.applicant}
                className="h-[62px] border-b border-[#D6D6D6] text-[11px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[12px]">{decision.applicant}</td>
                <td className="px-[12px]">{decision.type}</td>
                <td className="px-[12px]">{decision.decision}</td>
                <td className="px-[12px]">{decision.reviewer}</td>
                <td className="whitespace-nowrap px-[12px]">May 19,2026 at 09:15am</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[10px] p-[16px]">
        <h2 className="text-[12px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          Coastal Bites Limited address visit failed GPS and occupants checks - held pending a
          follow-up visit rather than an outright rejection
        </p>
      </div>
    </div>
  );
}

function AgentFloatPayoutReport() {
  const agents = [
    {
      name: "Ada Cash Point",
      balance: "₦306,000",
      topUps: "0",
      payout: "₦30,000",
      discrepancies: "None",
    },
    {
      name: "Femi Express Agent",
      balance: "₦260,000",
      topUps: "0",
      payout: "₦20,000",
      discrepancies: "None",
    },
    {
      name: "Northside Agency",
      balance: "₦0",
      topUps: "1 - Pending",
      payout: "₦36,000",
      discrepancies: "None",
    },
    { name: "Delta cash", balance: "₦0", topUps: "0", payout: "₦0", discrepancies: "Flagged" },
    {
      name: "Sulupoint Agency",
      balance: "₦306,000",
      topUps: "1 - Pending",
      payout: "₦46,000",
      discrepancies: "None",
    },
  ];

  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[24px] p-[16px]">
        <div className="grid grid-cols-2 gap-[16px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-AGE" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[11px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[11px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> ₦156,000 in commission
          payouts processed across 3 agents this period. 1 discrepancy remains open and escalated.
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[760px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[20%]" />
            <col className="w-[16%]" />
            <col className="w-[19%]" />
            <col className="w-[21%]" />
            <col className="w-[24%]" />
          </colgroup>
          <thead>
            <tr className="h-[54px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[12px] font-semibold text-[#6C6C6C]">
              <th className="px-[12px]" scope="col">
                Agents
              </th>
              <th className="px-[12px]" scope="col">
                Float Balance
              </th>
              <th className="px-[12px]" scope="col">
                Float Top-ups
              </th>
              <th className="px-[12px]" scope="col">
                Payout Processed
              </th>
              <th className="px-[12px]" scope="col">
                Discrepancies
              </th>
            </tr>
          </thead>
          <tbody>
            {agents.map((agent) => (
              <tr
                key={agent.name}
                className="h-[62px] border-b border-[#D6D6D6] text-[11px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[12px]">{agent.name}</td>
                <td className="px-[12px]">{agent.balance}</td>
                <td className="px-[12px]">{agent.topUps}</td>
                <td className="px-[12px]">{agent.payout}</td>
                <td className="px-[12px]">{agent.discrepancies}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[10px] p-[16px]">
        <h2 className="text-[12px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          Delta Cash (AG-119): ₦14,200 reconciliation mismatch, escalated to Finance &amp; Risk -
          float suspended pending resolution.
        </p>
      </div>
    </div>
  );
}

function DailyOpsSummaryReport() {
  const queues = [
    { name: "KYC Reviews", pending: 6, resolved: 2 },
    { name: "Merchant Applications", pending: 2, resolved: 0 },
    { name: "Agent Float Requests", pending: 1, resolved: 0 },
    { name: "Open Disputes", pending: 3, resolved: 1 },
  ];
  const actions = [
    "Approved KYC for Ibrahim Musa",
    "Suspended Yusuf Garba - Fraud flag",
    "Processed ₦340,000 payout to Obi & Co Field Team",
    "Escalated AG-119 to Finance & Risk",
  ];

  return (
    <div className="overflow-hidden rounded-[12px] border border-[#E5E7EB] bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
      <div className="flex h-[52px] items-center bg-[#00574D] px-[20px]">
        <div className="flex items-center gap-[6px] ">
          <span className="flex h-[22px] w-[22px] items-center justify-center rounded-full bg-white">
            <OnionTableIcon />
          </span>
          <span className="text-[14px] font-semibold text-white">nionloop</span>
        </div>
      </div>

      <div className="space-y-[24px] p-[16px]">
        <div className="grid grid-cols-2 gap-[16px] md:grid-cols-4">
          {[
            { label: "Report ID:", value: "Ops-267-DAI" },
            { label: "Period:", value: "19 June - 18 July 2026" },
            { label: "Generated By:", value: "Adaeze Chukwu,Operations" },
            { label: "Generated:", value: "Just now" },
          ].map((item) => (
            <div key={item.label} className="space-y-[6px]">
              <p className="text-[11px] text-[#8A8A8A]">{item.label}</p>
              <p className="text-[11px] font-semibold text-[#363636]">{item.value}</p>
            </div>
          ))}
        </div>

        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          <span className="font-semibold text-[#04907E]">SUMMARY:</span> 4 active queues today; KYC
          and disputes remain the primary workload. No SLA breaches recorded. 1 case escalated to
          Finance &amp; Risk
        </p>
      </div>

      <div className="w-full overflow-x-auto">
        <table className="w-full min-w-[560px] table-fixed border-collapse text-left">
          <colgroup>
            <col className="w-[50%]" />
            <col className="w-[27%]" />
            <col className="w-[23%]" />
          </colgroup>
          <thead>
            <tr className="h-[54px] border-y border-[#D6D6D6] bg-[#F7F7F7] text-[12px] font-semibold text-[#6C6C6C]">
              <th className="px-[12px]" scope="col">
                Queue
              </th>
              <th className="px-[12px]" scope="col">
                Pending
              </th>
              <th className="px-[12px]" scope="col">
                Resolved
              </th>
            </tr>
          </thead>
          <tbody>
            {queues.map((queue) => (
              <tr
                key={queue.name}
                className="h-[55px] border-b border-[#D6D6D6] text-[11px] text-[#6C6C6C] last:border-b-0"
              >
                <td className="px-[12px]">{queue.name}</td>
                <td className="px-[12px]">{queue.pending}</td>
                <td className="px-[12px]">{queue.resolved}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="space-y-[12px] border-b border-[#D6D6D6] p-[16px]">
        <h2 className="text-[12px] font-semibold text-[#04907E]">Actions Taken Today</h2>
        <ul className="list-inside list-disc space-y-[8px] text-[11px] leading-[18px] text-[#6C6C6C]">
          {actions.map((action) => (
            <li key={action}>{action}</li>
          ))}
        </ul>
      </div>

      <div className="space-y-[10px] p-[16px]">
        <h2 className="text-[12px] font-semibold text-[#04907E]">Notes &amp; Exceptions</h2>
        <p className="text-[11px] leading-[18px] text-[#6C6C6C]">
          Delta Cash (AG-119) exceeds Ops ₦10,000 self resolution limit and awaits Finance &amp;
          Risk action - flagged for follow-up tomorrow if unresolved
        </p>
      </div>
    </div>
  );
}

export default function ReportsDetails({ reportId }: ReportsDetailsProps) {
  const isDisputeReport = reportId === "dispute-resolution-log-pdf";
  const isAggregatorReport = reportId === "aggregator-commission-report-xlsx";
  const isMerchantReport = reportId === "merchant-onboarding-report-csv";
  const isKycReport = reportId === "kyc-approval-log-csv";
  const isAgentFloatReport = reportId === "agent-float-payout-report-csv";
  const isDailyOpsReport = reportId === "daily-ops-summary-csv";

  if (
    !isDisputeReport &&
    !isAggregatorReport &&
    !isMerchantReport &&
    !isKycReport &&
    !isAgentFloatReport &&
    !isDailyOpsReport
  ) {
    return <p className="text-[14px] text-[#6C6C6C]">This report preview is not available yet.</p>;
  }

  const reportTitle = isDisputeReport
    ? "Dispute Resolution Log (PDF)"
    : isAggregatorReport
      ? "Aggregator Commission Report (XLSX)"
      : isMerchantReport
        ? "Merchant Onboarding Report (CSV)"
        : isKycReport
          ? "KYC Approval Log (CSV)"
          : isAgentFloatReport
            ? "Agent Float & Payout Report (CSV)"
            : "Daily Ops Summary (CSV)";
  const reportName = isDisputeReport
    ? "Dispute Resolution Log"
    : isAggregatorReport
      ? "Aggregator Commission Report"
      : isMerchantReport
        ? "Merchant Onboarding Report"
        : isKycReport
          ? "KYC Approval Log"
          : isAgentFloatReport
            ? "Agent Float & Payout Report"
            : "Daily Ops Summary";
  const reportFormat = isDisputeReport ? "PDF" : isAggregatorReport ? "XLSX" : "CSV";

  return (
    <div className="space-y-[20px]">
      <div className="flex flex-wrap items-end justify-between gap-[16px]">
        <div className="space-y-[12px]">
          <Breadcrumb firstTab="Reports" secondTab={reportName} firstLink="/reports" />
          <div className="space-y-[4px]">
            <h1 className="text-[24px] font-semibold text-[#131313]">{reportTitle}</h1>
            <p className="text-[14px] text-[#6C6C6C]">Prepared for executive leadership</p>
          </div>
        </div>

        <Button
          variant="primary"
          size="md"
          className="h-[40px] rounded-[6px] bg-[#00574D] px-[16px] text-[14px]"
          icon={
            <svg
              width="16"
              height="16"
              viewBox="0 0 16 16"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
            >
              <path
                d="M8 2.25V9.25M8 9.25L5.25 6.5M8 9.25L10.75 6.5M3 10V12.25C3 12.8023 3.44772 13.25 4 13.25H12C12.5523 13.25 13 12.8023 13 12.25V10"
                stroke="white"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          }
        >
          Download {reportFormat}
        </Button>
      </div>

      {isDisputeReport ? (
        <DisputeResolutionReport />
      ) : isAggregatorReport ? (
        <AggregatorCommissionReport />
      ) : isMerchantReport ? (
        <MerchantOnboardingReport />
      ) : isKycReport ? (
        <KycApprovalReport />
      ) : isAgentFloatReport ? (
        <AgentFloatPayoutReport />
      ) : (
        <DailyOpsSummaryReport />
      )}

      <p className="text-[11px] text-[#6C6C6C]">
        System-generated from live operational data prepared by Adaeze Chukwu - Onionloop Operations
        - Internal use only, not for external distribution.
      </p>
    </div>
  );
}
